### ISSUE TITLE
ModuleNotFoundError: No module named 'ComfyUI-Paint3D-Nodes.Paint3D.paint3d'

### ISSUE THREAD

**Issue by zhaowtVincent** [N3rd00d/ComfyUI-Paint3D-Nodes#4]
I have this problem when I load, how can I solve it? Thank you.

![image](https://github.com/user-attachments/assets/3a4ba9bc-a949-4dc6-8b4d-5a14b9b67d34)

Warn!: Traceback (most recent call last):
  File "K:\software\ComfyU\comfyui_717\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1941, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "K:\software\ComfyU\comfyui_717\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Paint3D-Nodes\__init__.py", line 1, in <module>
    from .nodes import NODE_CLASS_MAPPINGS
  File "K:\software\ComfyU\comfyui_717\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Paint3D-Nodes\nodes.py", line 15, in <module>
    from .Paint3D.paint3d import utils
ModuleNotFoundError: No module named 'ComfyUI-Paint3D-Nodes.Paint3D.paint3d'

**Comment by N3rd00d** [comment]
Due to an internal Git cache issue, the Paint3D source code was not committed correctly. Please fetch the latest commit and try running it again.
