### ISSUE TITLE
When I run the workflow provided by the project, an error occurs

### ISSUE THREAD

**Issue by zhaowtVincent** [N3rd00d/ComfyUI-Paint3D-Nodes#5]
Thank you very much for porting paint3d to comfyui, but I get this error when running it, can you help me solve it?

!!! Exception during processing !!! pic should be PIL Image or ndarray. Got <class 'int'>
Traceback (most recent call last):
  File "K:\software\ComfyU\0728\ComfyUI_Windows_portable\ComfyUI\execution.py", line 316, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "K:\software\ComfyU\0728\ComfyUI_Windows_portable\ComfyUI\execution.py", line 191, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "K:\software\ComfyU\0728\ComfyUI_Windows_portable\ComfyUI\execution.py", line 168, in _map_node_over_list
    process_inputs(input_dict, i)
  File "K:\software\ComfyU\0728\ComfyUI_Windows_portable\ComfyUI\execution.py", line 157, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "K:\software\ComfyU\0728\ComfyUI_Windows_portable\ComfyUI\custom_nodes\ComfyUI-Paint3D-Nodes\nodes.py", line 529, in project
    albedo = to_tensor_image(albedo)
             ^^^^^^^^^^^^^^^^^^^^^^^
  File "K:\software\ComfyU\0728\ComfyUI_Windows_portable\ComfyUI\custom_nodes\ComfyUI-Paint3D-Nodes\nodes.py", line 66, in to_tensor_image
    tensor_image = to_tensor(image)
                   ^^^^^^^^^^^^^^^^
  File "K:\software\ComfyU\0728\ComfyUI_Windows_portable\python_embeded\Lib\site-packages\torchvision\transforms\transforms.py", line 137, in __call__
    return F.to_tensor(pic)
           ^^^^^^^^^^^^^^^^
  File "K:\software\ComfyU\0728\ComfyUI_Windows_portable\python_embeded\Lib\site-packages\torchvision\transforms\functional.py", line 142, in to_tensor
    raise TypeError(f"pic should be PIL Image or ndarray. Got {type(pic)}")
TypeError: pic should be PIL Image or ndarray. Got <class 'int'>

Prompt executed in 11.79 seconds
No pending upload

**Comment by N3rd00d** [comment]
Due to an internal Git cache issue, the Paint3D source code was not committed correctly. Please fetch the latest commit and try running it again.

**Comment by Ma0013** [comment]
I also want to thank you for the paint3d nodes. Same as @zhaowtVincent i have a similar issue with the 3D_projection node. 
`Error occurred when executing 3D_Projection:
pic should be PIL Image or ndarray. Got 

  File "/workspace/ComfyUI/execution.py", line 152, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "/workspace/ComfyUI/execution.py", line 82, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "/workspace/ComfyUI/execution.py", line 75, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "/workspace/ComfyUI/custom_nodes/ComfyUI-Paint3D-Nodes/nodes.py", line 527, in project
    albedo = to_tensor_image(albedo)
  File "/workspace/ComfyUI/custom_nodes/ComfyUI-Paint3D-Nodes/nodes.py", line 66, in to_tensor_image
    tensor_image = to_tensor(image)
  File "/usr/local/lib/python3.10/dist-packages/torchvision/transforms/transforms.py", line 137, in __call__
    return F.to_tensor(pic)
  File "/usr/local/lib/python3.10/dist-packages/torchvision/transforms/functional.py", line 140, in to_tensor
    raise TypeError(f"pic should be PIL Image or ndarray. Got {type(pic)}")`
